baseURL = 'https://yonaisy-arts.nl/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-cards'

[params.post.meta]
isHidden = true

[params.post.sidebar]
type = "profile"
title = "Profile"